//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMSV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilePicture
    {
        public int PictureId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FileName { get; set; }
        public string Type { get; set; }
        public Nullable<int> Size { get; set; }
        public string DATA { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
